CREATE DATABASE IF NOT EXISTS `notes` DEFAULT CHARACTER SET `utf8` DEFAULT COLLATE `utf8_persian_ci`;
USE `notes`;

CREATE TABLE IF NOT EXISTS `users` (
    `id` VARCHAR(255) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `phonenumber` VARCHAR(15) NULL,
    `password` VARCHAR(255) NULL,
    `type` TINYTEXT DEFAULT 'user',
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` DEFAULT COLLATE `utf8_persian_ci`;

CREATE TABLE IF NOT EXISTS `note` (
    `id` VARCHAR(255) NOT NULL,
    `uid` VARCHAR(255) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `text` VARCHAR(1255) NOT NULL,
    `updateAt` TIMESTAMP ,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` DEFAULT COLLATE `utf8_persian_ci`;

CREATE TABLE IF NOT EXISTS `chats` (
    `id` VARCHAR(255) NOT NULL,
    `uid` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `chat` VARCHAR(1255) NOT NULL,
    `status` INT(10) NOT NULL DEFAULT 0,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET `utf8` DEFAULT COLLATE `utf8_persian_ci`;

